apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-ci-cd
  template:
    metadata:
      labels:
        app: go-ci-cd
    spec:
      containers:
      - name: go-ci-cd
        image: go-ci-cd:latest
        ports:
        - containerPort: 8080