name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod tidy

      - name: Run the pipeline
        run: go run main.go --config=config/pipeline.yaml

      - name: Build Docker image
        run: docker build -t go-ci-cd .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/k8s.yaml